
# Highly divisible triangular number
# Problem 12

# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#      1: 1
#      3: 1,3
#      6: 1,2,3,6
#     10: 1,2,5,10
#     15: 1,3,5,15
#     21: 1,3,7,21
#     28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

import math
import itertools

def factors(n):
    """finds all the factors in number n and returns a list of all the factors"""
    sqrt = int(math.floor(math.sqrt(n)))
    print "number is", n
    # print "square root of the number is about", sqrt

    smaller_factors = set()
    all_factors = set()

    for i in xrange(1,sqrt+1):
        if n % i == 0:
            smaller_factors.add(i)

    for i in smaller_factors:
        all_factors.add(n/i)
    all_factors = all_factors.union(smaller_factors)
    print all_factors

    return all_factors

# for i in range(20):
#     factors(i)


def triangle_numbers():
    start = 1
    total = 0

    while True:
        total += start
        print "start", start, "total", total
        yield total
        start += 1

iterator = triangle_numbers()

for i in range(10):
    print iterator.next()

while True:
    number = iterator.next()
    factors(number)
    print "FACTORS OF THE NUMBER ARE", factors(number)
    if len(factors(number)) > 500:
        break

    # if number > 500:
    #     break
print "the winner is", number

# print factors(100)
# print len(factors(100))