# Even Fibonacci numbers
# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

past1 = 2
past2 = 1
current = 0
total = 2
n = 100


for i in range(n):
	current = past1 + past2
	if (current > 4000000):
		break
	print "Fibbnacci number ", i+3, " is ", current
	past2 = past1
	past1 = current
	if (current%2 == 0):
		total += current

print "total of even numbered Fibonacci numbers is ", total